apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: calculator
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: srbino/testing_environment:latest
        ports:
        - containerPort: 5000
